config/routes.rb
FlorDeSabao::Application.routes.draw do
  get "landings/index"
  resources :products

  resources :materials

  resources :characteristics

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/characteristic.rb
class Characteristic < ActiveRecord::Base
  has_and_belongs_to_many :products
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :set_characteristic, only: [:show, :edit, :update, :destroy]

  # GET /characteristics
  # GET /characteristics.json
  def index
    @characteristics = Characteristic.all
  end

  # GET /characteristics/1
  # GET /characteristics/1.json
  def show
  end

  # GET /characteristics/new
  def new
    @characteristic = Characteristic.new
  end

  # GET /characteristics/1/edit
  def edit
  end

  # POST /characteristics
  # POST /characteristics.json
  def create
    @characteristic = Characteristic.new(characteristic_params)

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @characteristic }
      else
        format.html { render action: 'new' }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characteristics/1
  # PATCH/PUT /characteristics/1.json
  def update
    respond_to do |format|
      if @characteristic.update(characteristic_params)
        format.html { redirect_to @characteristic, notice: 'Characteristic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1
  # DELETE /characteristics/1.json
  def destroy
    @characteristic.destroy
    respond_to do |format|
      format.html { redirect_to characteristics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic
      @characteristic = Characteristic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def characteristic_params
      params.require(:characteristic).permit(:name, :value)
    end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/views/characteristics/_form.html.erb
<%= form_for @characteristic, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :value, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :value, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  characteristics_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/characteristics/edit.html.erb
<%- model_class = Characteristic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Characteristic %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characteristics/index.html.erb
<%- model_class = Characteristic -%>
<div class="page-header">
  <h1><%=t '.title', :default => Characteristic %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @characteristics.each do |characteristic| %>
      <tr>
        <td><%= characteristic.id %></td>
        <td><%= characteristic.name %></td>
        <td><%= characteristic.value %></td>
        <td><%=l characteristic.created_at, format: :long %></td>
        <td>
          <%= link_to characteristic_path(characteristic), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to characteristic_path(characteristic), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_characteristic_path,
            :class => 'btn btn-primary' %>

app/views/characteristics/new.html.erb
<%- model_class = Characteristic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Characteristic %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characteristics/show.html.erb
<%- model_class = Characteristic -%>
<div class="page-header">
  <h1><%=t '.title', :default => Characteristic %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @characteristic.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:value) %></dt>
      <dd><pre class="prettyprint"><%= @characteristic.value %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              characteristics_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_characteristic_path(@characteristic), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              characteristic_path(@characteristic),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>