config/routes.rb
FlorDeSabao::Application.routes.draw do
  get "landings/index"
  resources :products

  resources :materials

  resources :characteristics

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/material.rb
class Material < ActiveRecord::Base
  has_and_belongs_to_many :products
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render action: 'show', status: :created, location: @material }
      else
        format.html { render action: 'new' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :price, :quantity, :unit, :volume, :suplier, :minimum_stock)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for @material, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :price, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :quantity, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :unit, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :volume, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :volume, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :suplier, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :suplier, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :minimum_stock, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :minimum_stock, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  materials_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/materials/edit.html.erb
<%- model_class = Material -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Material %></h1>
</div>
<%= render :partial => 'form' %>

app/views/materials/index.html.erb
<%- model_class = Material -%>
<div class="page-header">
  <h1><%=t '.title', :default => Material %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:unit) %></th>
      <th><%= model_class.human_attribute_name(:volume) %></th>
      <th><%= model_class.human_attribute_name(:suplier) %></th>
      <th><%= model_class.human_attribute_name(:minimum_stock) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.id %></td>
        <td><%= material.name %></td>
        <td><%= material.price %></td>
        <td><%= material.quantity %></td>
        <td><%= material.unit %></td>
        <td><%= material.volume %></td>
        <td><%= material.suplier %></td>
        <td><%= material.minimum_stock %></td>
        <td><%=l material.created_at, format: :long %></td>
        <td>
          <%= link_to material_path(material), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to material_path(material), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_material_path,
            :class => 'btn btn-primary' %>

app/views/materials/new.html.erb
<%- model_class = Material -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Material %></h1>
</div>
<%= render :partial => 'form' %>

app/views/materials/show.html.erb
<%- model_class = Material -%>
<div class="page-header">
  <h1><%=t '.title', :default => Material %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @material.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:price) %></dt>
      <dd><pre class="prettyprint"><%= @material.price %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:quantity) %></dt>
      <dd><pre class="prettyprint"><%= @material.quantity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:unit) %></dt>
      <dd><pre class="prettyprint"><%= @material.unit %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:volume) %></dt>
      <dd><pre class="prettyprint"><%= @material.volume %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:suplier) %></dt>
      <dd><pre class="prettyprint"><%= @material.suplier %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:minimum_stock) %></dt>
      <dd><pre class="prettyprint"><%= @material.minimum_stock %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              materials_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_material_path(@material), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              material_path(@material),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>